spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql://192.168.6.36:3306/spring-boot?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456

  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

  data:
    mongodb:
      uri: mongodb://192.168.6.36:27017/spring-boot
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

  cache:
    type: redis

  redis:
    url: http://192.168.6.36:6379

  rabbitmq:
    host: 192.168.6.36
    port: 5672
    username: guest
    password: 123456

  thymeleaf:
    mode: LEGACYHTML5

security:
  basic:
    enabled: false
  oauth2:
    resource:
      id: spring-boot
      filter-order: 3
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtcrMpo3qSUBunWCcvyQ1
          i8agSUpJrU/6ZN9xtlqSTL5lCne51rU1ikAmubw3rmZIQP7s8kOPXJJgvANloY+J
          wj793FnMHnK51Se86+yHSnqrR6CdMMF77y8hEc4BIRqIcgCLUTk2FaEiYSGki01N
          58l+n0tdHLW6vSc75Yz9IuG3iiI+HA5CKdSEWHT6DlZ4m8VUzxYmGEMIRfqAdDSO
          5EHIjQJJOhssnNfs5CXL7i7h/6VktriFIPg+3hnqbhrHhea+qT081Czv8I5/gjTG
          +8o7qrN5Di3TOTZynACcAC7hcfCxmwOequa/LrGWXaS6J0pz+8WijZuAyNBqNujn
          ZQIDAQAB
          -----END PUBLIC KEY-----
#debug: true

